export {default as Home} from './Home'
export {default as PantallaInicio} from './PantallaInicio'
export {default as Test} from './Test'
export {default as TestQuestions} from './TestQuestions'
export {default as Perfil} from './Perfil'
export {default as Juego} from './Juego'
export {default as JuegoPlay} from './JuegoPlay'